USE [master]
GO

/****** Object:  Database [UnivaEats]    Script Date: 8/3/2019 2:36:55 AM ******/
CREATE DATABASE [UnivaEats]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'UnivaEats', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\UnivaEats.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'UnivaEats_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\UnivaEats_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [UnivaEats].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [UnivaEats] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [UnivaEats] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [UnivaEats] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [UnivaEats] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [UnivaEats] SET ARITHABORT OFF 
GO

ALTER DATABASE [UnivaEats] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [UnivaEats] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [UnivaEats] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [UnivaEats] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [UnivaEats] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [UnivaEats] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [UnivaEats] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [UnivaEats] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [UnivaEats] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [UnivaEats] SET  DISABLE_BROKER 
GO

ALTER DATABASE [UnivaEats] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [UnivaEats] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [UnivaEats] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [UnivaEats] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [UnivaEats] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [UnivaEats] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [UnivaEats] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [UnivaEats] SET RECOVERY FULL 
GO

ALTER DATABASE [UnivaEats] SET  MULTI_USER 
GO

ALTER DATABASE [UnivaEats] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [UnivaEats] SET DB_CHAINING OFF 
GO

ALTER DATABASE [UnivaEats] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [UnivaEats] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [UnivaEats] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [UnivaEats] SET QUERY_STORE = OFF
GO

ALTER DATABASE [UnivaEats] SET  READ_WRITE 
GO

USE [UnivaEats]
GO

/****** Object:  Table [dbo].[Pedidos]    Script Date: 8/3/2019 2:37:28 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Pedidos](
	[Pedidos_Matricula] [int] NULL,
	[Pedidos_Pedido] [nvarchar](500) NULL,
	[Pedidos_Total] [int] NULL,
	[Pedidos_Fecha] [datetime] NULL
) ON [PRIMARY]
GO

USE [UnivaEats]
GO

/****** Object:  Table [dbo].[Usuarios]    Script Date: 8/3/2019 2:37:53 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Usuarios](
	[Usuario_Matricula] [int] NULL,
	[Usuario_Nombre] [nvarchar](50) NULL,
	[Usuario_ApellidoPaterno] [nvarchar](50) NULL,
	[Usuario_ApellidoMaterno] [nvarchar](50) NULL,
	[Usuario_Password] [nvarchar](50) NULL,
	[Usuario_Tipo] [nvarchar](50) NULL
) ON [PRIMARY]
GO

